---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/crichton/public_html/test.crichton-ip.com.ng
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp assets $DEPLOYPATH